# Generated by Django 6.0.6 on 2026-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetBlog', '0003_alter_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='featured_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
