# Generated by Django 6.0.6 on 2026-06-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetBlog', '0005_alter_content_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True),
        ),
    ]
