# Generated by Django 6.0.6 on 2026-06-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetBlog', '0006_alter_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='blog_body',
            field=models.TextField(max_length=10500),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
